// cloudcart-frontend/components/Header.tsx
"use client";

import Link from "next/link";
import { useCart } from "@/lib/CartContext";

interface HeaderProps {
  userId: string | null;
  onChangeUser: () => void;
}

export default function Header({ userId, onChangeUser }: HeaderProps) {
  const { cartCount } = useCart();

  return (
    <header className="sticky top-0 z-40 w-full">
      {/* Main nav — solid deep brand gradient */}
      <div
        style={{
          background: "var(--cc-grad-header)",
          borderBottom: "1px solid rgba(99,102,241,0.35)",
          boxShadow: "0 4px 24px rgba(15,10,46,0.45)",
        }}
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">

            {/* Logo */}
            <Link
              href="/"
              className="flex items-center gap-2.5 group select-none"
              aria-label="CloudCart home"
            >
              {/* Icon mark */}
              <div
                className="w-9 h-9 rounded-xl flex items-center justify-center text-white text-lg font-black shadow-md group-hover:scale-105 transition-transform duration-150"
                style={{ background: "var(--cc-grad-brand)" }}
                aria-hidden="true"
              >
                C
              </div>
              <span
                className="text-xl font-black tracking-tight text-white"
              >
                CloudCart
              </span>
            </Link>

            {/* Right side controls */}
            <div className="flex items-center gap-2 sm:gap-4">

              {/* User chip */}
              {userId && (
                <div
                  className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium"
                  style={{
                    background: "rgba(255,255,255,0.12)",
                    border: "1px solid rgba(196,181,253,0.40)",
                    color: "#e0d9ff",
                  }}
                >
                  <span
                    className="w-2 h-2 rounded-full inline-block"
                    style={{ background: "var(--cc-violet-light)" }}
                    aria-hidden="true"
                  />
                  <span>{userId}</span>
                  <button
                    onClick={onChangeUser}
                    className="ml-1 text-xs underline underline-offset-2 opacity-70 hover:opacity-100 transition-opacity"
                    style={{ color: "#c4b5fd" }}
                    aria-label="Change user ID"
                  >
                    Change
                  </button>
                </div>
              )}

              {/* My Orders link */}
              <Link
                href="/orders"
                className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold transition-all duration-150"
                style={{ color: "#c4b5fd" }}
                onMouseEnter={(e) => {
                  (e.currentTarget as HTMLElement).style.background = "rgba(255,255,255,0.12)";
                  (e.currentTarget as HTMLElement).style.color = "#ffffff";
                }}
                onMouseLeave={(e) => {
                  (e.currentTarget as HTMLElement).style.background = "transparent";
                  (e.currentTarget as HTMLElement).style.color = "#c4b5fd";
                }}
              >
                <svg
                  className="w-4 h-4"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
                  />
                </svg>
                Orders
              </Link>

              {/* Cart button — orange gradient for high contrast on dark header */}
              <Link
                href="/cart"
                className="relative flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold text-white transition-all duration-150 hover:scale-105 active:scale-95"
                style={{
                  background: "var(--cc-grad-orange)",
                  boxShadow: "var(--cc-shadow-btn-orange)",
                }}
                aria-label={`Cart${cartCount > 0 ? `, ${cartCount} items` : ""}`}
              >
                <svg
                  className="w-4 h-4"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2.5"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
                  />
                </svg>
                <span className="hidden sm:inline">Cart</span>
                {cartCount > 0 && (
                  <span
                    className="absolute -top-2 -right-2 min-w-[1.25rem] h-5 px-1 flex items-center justify-center text-xs font-black rounded-full text-white cc-pulse-ring"
                    style={{ background: "#7c3aed", boxShadow: "0 2px 8px rgba(124,58,237,0.6)" }}
                    aria-hidden="true"
                  >
                    {cartCount > 99 ? "99+" : cartCount}
                  </span>
                )}
              </Link>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}

// cloudcart-angular/src/app/shared/components/header/header.component.ts
import { Component, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CartService } from '../../../core/services/cart.service';
import { UserService } from '../../../core/services/user.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, FormsModule],
  templateUrl: './header.component.html'
})
export class HeaderComponent {
  cartService = inject(CartService);
  userService = inject(UserService);

  editingUserId = signal<boolean>(false);
  tempUserId = signal<string>('');

  startEdit(): void {
    this.tempUserId.set(this.userService.userId());
    this.editingUserId.set(true);
  }

  saveUserId(): void {
    this.userService.setUserId(this.tempUserId());
    this.editingUserId.set(false);
    this.cartService.loadCart();
  }

  cancelEdit(): void {
    this.editingUserId.set(false);
  }

  setNavHover(event: MouseEvent, hovering: boolean): void {
    const el = event.currentTarget as HTMLElement;
    el.style.background = hovering ? 'rgba(255,255,255,0.10)' : 'transparent';
    el.style.color = hovering ? '#ffffff' : '#c4b5fd';
  }
}

<header class="sticky top-0 z-40 w-full">
  <div style="background: var(--cc-grad-header); border-bottom: 1px solid rgba(99,102,241,0.35); box-shadow: 0 4px 24px rgba(15,10,46,0.55);">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">

        <!-- Logo -->
        <a routerLink="/" class="flex items-center gap-2.5 group select-none" aria-label="CloudCart home">
          <div
            class="w-9 h-9 rounded-xl flex items-center justify-center text-white text-lg font-black shadow-md group-hover:scale-105 transition-transform duration-150"
            style="background: var(--cc-grad-brand);"
            aria-hidden="true"
          >C</div>
          <span class="text-xl font-black tracking-tight text-white">CloudCart</span>
        </a>

        <!-- Right side controls -->
        <div class="flex items-center gap-2 sm:gap-3">

          <!-- User chip (non-edit mode) -->
          @if (!editingUserId()) {
            <div
              class="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium"
              style="background: rgba(255,255,255,0.1); border: 1px solid rgba(196,181,253,0.35); color: #e0d9ff;"
            >
              <span class="w-2 h-2 rounded-full inline-block" style="background: var(--cc-violet-light);" aria-hidden="true"></span>
              <span class="max-w-24 truncate">{{ userService.userId() }}</span>
              <button
                (click)="startEdit()"
                class="ml-1 text-xs underline underline-offset-2 opacity-70 hover:opacity-100 transition-opacity"
                style="color: #c4b5fd;"
                aria-label="Change user ID"
              >Change</button>
            </div>
          }

          <!-- User chip (edit mode) -->
          @if (editingUserId()) {
            <div class="hidden sm:flex items-center gap-1.5">
              <input
                [ngModel]="tempUserId()"
                (ngModelChange)="tempUserId.set($event)"
                (keyup.enter)="saveUserId()"
                (keyup.escape)="cancelEdit()"
                class="w-28 px-2.5 py-1 rounded-lg text-xs text-white focus:outline-none focus:ring-1 focus:ring-violet-400"
                style="background: rgba(30,27,75,0.9); border: 1px solid rgba(124,58,237,0.5);"
                placeholder="User ID"
                aria-label="Edit user ID"
                autofocus
              />
              <button
                (click)="saveUserId()"
                class="text-xs font-bold px-2 py-1 rounded-md transition-colors"
                style="color: #34d399; background: rgba(5,150,105,0.15); border: 1px solid rgba(5,150,105,0.3);"
              >Save</button>
              <button
                (click)="cancelEdit()"
                class="text-xs font-bold px-2 py-1 rounded-md transition-colors"
                style="color: #f87171; background: rgba(220,38,38,0.12); border: 1px solid rgba(220,38,38,0.25);"
              >Cancel</button>
            </div>
          }

          <!-- My Orders link -->
          <a
            routerLink="/orders"
            class="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-semibold transition-all duration-150"
            style="color: #c4b5fd;"
            (mouseenter)="setNavHover($event, true)"
            (mouseleave)="setNavHover($event, false)"
          >
            <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
            Orders
          </a>

          <!-- Cart button — orange gradient for high contrast on dark header -->
          <a
            routerLink="/cart"
            class="relative flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold text-white transition-all duration-150 hover:scale-105 active:scale-95"
            style="background: var(--cc-grad-orange); box-shadow: var(--cc-shadow-btn-orange);"
            [attr.aria-label]="cartService.cartCount() > 0 ? 'Cart, ' + cartService.cartCount() + ' items' : 'Cart'"
          >
            <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <span class="hidden sm:inline">Cart</span>

            @if (cartService.cartCount() > 0) {
              <span
                class="cart-badge absolute -top-2 -right-2 min-w-5 h-5 px-1 flex items-center justify-center text-xs font-black rounded-full text-white cc-pulse-ring"
                style="background: #7c3aed; box-shadow: 0 2px 8px rgba(124,58,237,0.7);"
                aria-hidden="true"
              >
                {{ cartService.cartCount() > 99 ? '99+' : cartService.cartCount() }}
              </span>
            }
          </a>

        </div>
      </div>
    </div>
  </div>
</header>
