// cloudcart-angular/src/app/pages/checkout/checkout.component.ts
import { Component, OnInit, OnDestroy, inject, signal, computed } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { CartService } from '../../core/services/cart.service';
import { OrderService } from '../../core/services/order.service';
import { UserService } from '../../core/services/user.service';
import { Order } from '../../core/models/order.model';

@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './checkout.component.html'
})
export class CheckoutComponent implements OnInit, OnDestroy {
  private cartService = inject(CartService);
  private orderService = inject(OrderService);
  private userService = inject(UserService);
  private router = inject(Router);

  cartItems = this.cartService.cartItems;
  total = computed(() =>
    this.cartItems().reduce((sum, i) => sum + i.price * i.quantity, 0)
  );
  totalQty = computed(() =>
    this.cartItems().reduce((sum, i) => sum + i.quantity, 0)
  );

  statusGradient = computed(() => {
    const s = this.orderStatus();
    if (s === 'PAID' || s === 'SHIPMENT_CREATED' || s === 'SHIPPED')
      return 'linear-gradient(135deg, #059669, #10b981)';
    if (s === 'FAILED') return 'linear-gradient(135deg, #dc2626, #ef4444)';
    return 'linear-gradient(135deg, #d97706, #f59e0b)';
  });

  statusBgColor = computed(() => {
    const s = this.orderStatus();
    if (s === 'PAID' || s === 'SHIPMENT_CREATED' || s === 'SHIPPED')
      return 'rgba(5,150,105,0.1)';
    if (s === 'FAILED') return 'rgba(220,38,38,0.1)';
    return 'rgba(217,119,6,0.1)';
  });

  statusBorderColor = computed(() => {
    const s = this.orderStatus();
    if (s === 'PAID' || s === 'SHIPMENT_CREATED' || s === 'SHIPPED')
      return 'rgba(52,211,153,0.35)';
    if (s === 'FAILED') return 'rgba(220,38,38,0.35)';
    return 'rgba(245,158,11,0.35)';
  });

  statusTextColor = computed(() => {
    const s = this.orderStatus();
    if (s === 'PAID' || s === 'SHIPMENT_CREATED' || s === 'SHIPPED') return '#34d399';
    if (s === 'FAILED') return '#fca5a5';
    return '#fcd34d';
  });

  statusLabel = computed(() => {
    switch (this.orderStatus()) {
      case 'SHIPMENT_CREATED': return 'Shipment Created';
      case 'PAID':             return 'Payment Successful';
      case 'PENDING':          return 'Processing Payment';
      case 'FAILED':           return 'Payment Failed';
      case 'SHIPPED':          return 'Order Shipped';
      default:                 return 'Order Submitted';
    }
  });

  statusDetail = computed(() => {
    switch (this.orderStatus()) {
      case 'SHIPMENT_CREATED':
        return 'Your order has been confirmed and a shipment is being prepared.';
      case 'PAID':
        return 'Payment was processed successfully. Your order is confirmed.';
      case 'PENDING':
        return 'Payment is being processed. This page updates automatically.';
      case 'FAILED':
        return 'The payment could not be processed. Please try again.';
      case 'SHIPPED':
        return 'Your order is on its way!';
      default:
        return 'Order is being processed — check back shortly in My Orders.';
    }
  });

  placing = signal<boolean>(false);
  orderId = signal<string | null>(null);
  orderStatus = signal<string | null>(null);
  orderData = signal<Order | null>(null);
  error = signal<string | null>(null);
  pollCount = signal<number>(0);

  private pollSub?: Subscription;
  private readonly MAX_POLLS = 20;

  ngOnInit(): void {
    this.cartService.loadCart();
  }

  ngOnDestroy(): void {
    this.stopPolling();
  }

  placeOrder(): void {
    if (this.placing() || this.cartItems().length === 0) return;
    this.placing.set(true);
    this.error.set(null);

    const request = {
      userId: this.userService.userId(),
      items: this.cartItems().map(i => ({
        productId: i.productId,
        quantity: i.quantity,
        price: i.price
      }))
    };

    this.orderService.placeOrder(request).subscribe({
      next: (res) => {
        this.orderId.set(res.orderId);
        this.orderStatus.set('PENDING');
        this.placing.set(false);
        this.startPolling(res.orderId);
      },
      error: (err) => {
        this.error.set(err.error?.message ?? 'Failed to place order. Please try again.');
        this.placing.set(false);
      }
    });
  }

  private startPolling(orderId: string): void {
    let delay = 2000;
    const poll = () => {
      if (this.pollCount() >= this.MAX_POLLS) {
        this.stopPolling();
        return;
      }
      this.orderService.getOrder(orderId, this.userService.userId()).subscribe({
        next: (order) => {
          this.orderData.set(order);
          this.orderStatus.set(order.status);
          this.pollCount.update(c => c + 1);

          if (['PAID', 'SHIPPED', 'SHIPMENT_CREATED', 'FAILED'].includes(order.status)) {
            this.stopPolling();
            if (order.status !== 'FAILED') {
              this.cartService.clearCart();
            }
          } else {
            delay = Math.min(delay * 1.2, 5000);
            setTimeout(poll, delay);
          }
        },
        error: () => {
          this.pollCount.update(c => c + 1);
          if (this.pollCount() < this.MAX_POLLS) {
            setTimeout(poll, delay);
          }
        }
      });
    };
    setTimeout(poll, delay);
  }

  private stopPolling(): void {
    this.pollSub?.unsubscribe();
  }

  getStatusStep(): number {
    const s = this.orderStatus();
    if (s === 'PAID') return 2;
    if (s === 'SHIPMENT_CREATED' || s === 'SHIPPED') return 3;
    return 1;
  }
}

<div class="max-w-2xl mx-auto cc-fade-up">

  <!-- ── Checkout form ─────────────────────────────────────────── -->
  @if (!orderId()) {
    <div class="flex items-center justify-between mb-8">
      <div>
        <h1 class="text-3xl font-black" style="color: #f0ebff;">Checkout</h1>
        @if (cartItems().length > 0) {
          <p class="text-sm mt-0.5" style="color: #7c6fb0;">Review your order before placing it</p>
        }
      </div>
      <a
        routerLink="/cart"
        class="inline-flex items-center gap-1.5 text-sm font-semibold transition-colors duration-150"
        style="color: var(--cc-violet-light);"
      >
        <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
        </svg>
        Back to cart
      </a>
    </div>

    <!-- Empty cart -->
    @if (cartItems().length === 0) {
      <div
        class="flex flex-col items-center justify-center py-24 rounded-3xl border"
        style="border-color: rgba(124,58,237,0.35); background: rgba(30,27,75,0.4);"
      >
        <div
          class="w-16 h-16 rounded-2xl flex items-center justify-center mb-5"
          style="background: var(--cc-grad-brand);"
          aria-hidden="true"
        >
          <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
          </svg>
        </div>
        <p class="text-lg font-black mb-2" style="color: #f0ebff;">Your cart is empty</p>
        <a
          routerLink="/"
          class="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-bold text-white mt-2 transition-all hover:scale-105"
          style="background: var(--cc-grad-brand); box-shadow: var(--cc-shadow-btn);"
        >Browse products</a>
      </div>
    } @else {
      <div class="space-y-4">
        <!-- Order summary card -->
        <div
          class="rounded-2xl overflow-hidden"
          style="background: rgba(20,16,60,0.7); border: 1px solid rgba(99,102,241,0.2); box-shadow: var(--cc-shadow-sm);"
        >
          <div
            class="px-6 py-4 border-b"
            style="background: rgba(124,58,237,0.12); border-color: rgba(124,58,237,0.25);"
          >
            <h2 class="text-xs font-bold uppercase tracking-widest" style="color: #a78bfa;">
              Order Summary
            </h2>
          </div>
          <div class="px-6 py-4 divide-y" style="--tw-divide-opacity: 0.15;">
            @for (item of cartItems(); track item.productId) {
              <div class="flex justify-between items-center py-3">
                <div class="min-w-0">
                  <p class="text-sm font-semibold truncate" style="color: #e0d9ff;">
                    {{ item.title || item.productId }}
                  </p>
                  <p class="text-xs mt-0.5" style="color: #7c6fb0;">
                    Qty: {{ item.quantity }} &times; ${{ item.price.toFixed(2) }}
                  </p>
                </div>
                <span class="font-bold text-sm ml-4" style="color: #c4b5fd;">
                  ${{ (item.price * item.quantity).toFixed(2) }}
                </span>
              </div>
            }
          </div>
        </div>

        <!-- Total bar -->
        <div
          class="flex justify-between items-center px-6 py-4 rounded-2xl"
          style="background: rgba(124,58,237,0.12); border: 1px solid rgba(124,58,237,0.3);"
        >
          <span class="font-bold" style="color: #e0d9ff;">Total ({{ totalQty() }} item{{ totalQty() !== 1 ? 's' : '' }})</span>
          <span class="text-2xl font-black cc-gradient-text">${{ total().toFixed(2) }}</span>
        </div>

        <!-- Error -->
        @if (error()) {
          <div
            class="flex items-start gap-3 px-5 py-4 rounded-2xl border text-sm"
            style="background: rgba(220,38,38,0.1); border-color: rgba(220,38,38,0.35); color: #fca5a5;"
            role="alert"
          >
            <svg class="w-5 h-5 mt-0.5 shrink-0" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true">
              <circle cx="12" cy="12" r="10" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01" />
            </svg>
            <p>{{ error() }}</p>
          </div>
        }

        <!-- Place order button -->
        <button
          (click)="placeOrder()"
          [disabled]="placing()"
          class="w-full flex items-center justify-center gap-3 py-4 rounded-2xl text-base font-black text-white transition-all duration-150 disabled:opacity-60 disabled:cursor-not-allowed hover:scale-[1.02] hover:-translate-y-0.5 active:scale-[0.98]"
          style="background: var(--cc-grad-brand); box-shadow: var(--cc-shadow-btn);"
        >
          @if (placing()) {
            <span
              class="w-5 h-5 border-2 border-t-transparent rounded-full cc-spin"
              style="border-color: rgba(255,255,255,0.8);"
              aria-hidden="true"
            ></span>
            Placing Order&hellip;
          } @else {
            <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            Place Order &mdash; ${{ total().toFixed(2) }}
          }
        </button>

        <p class="text-center text-xs" style="color: #7c6fb0;">
          By placing your order you agree to our demo terms. All transactions are simulated.
        </p>
      </div>
    }
  }

  <!-- ── Order status screen ────────────────────────────────── -->
  @if (orderId()) {
    <div class="max-w-md mx-auto py-10" role="status" aria-live="polite">
      <div
        class="rounded-3xl overflow-hidden"
        [style.border]="'1px solid ' + statusBorderColor()"
        style="box-shadow: 0 8px 32px rgba(0,0,0,0.6);"
      >
        <!-- Colored header -->
        <div
          class="flex flex-col items-center justify-center gap-4 py-10 px-8"
          [style.background]="statusGradient()"
        >
          <!-- Status icon -->
          <div
            class="w-20 h-20 rounded-full flex items-center justify-center"
            style="background: rgba(255,255,255,0.18);"
          >
            @switch (orderStatus()) {
              @case ('PAID') {
                <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              }
              @case ('SHIPMENT_CREATED') {
                <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10" />
                </svg>
              }
              @case ('SHIPPED') {
                <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
                </svg>
              }
              @case ('FAILED') {
                <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              }
              @default {
                <!-- PENDING spinner -->
                <span
                  class="w-10 h-10 border-4 border-t-transparent rounded-full cc-spin inline-block"
                  style="border-color: rgba(255,255,255,0.85);"
                  aria-label="Processing"
                ></span>
              }
            }
          </div>
          <h2 class="text-2xl font-black text-white text-center">{{ statusLabel() }}</h2>
        </div>

        <!-- Details panel -->
        <div [style.background]="statusBgColor()" class="px-8 py-6 text-center space-y-4">
          <!-- Order ID badge -->
          <div
            class="inline-flex flex-col items-center gap-1 px-5 py-3 rounded-2xl border"
            [style.borderColor]="statusBorderColor()"
          >
            <p class="text-xs font-bold uppercase tracking-widest" [style.color]="statusTextColor()">
              Order ID
            </p>
            <p class="font-mono text-sm font-semibold" style="color: #e0d9ff;">
              {{ orderId() }}
            </p>
            <span
              class="mt-1 px-2.5 py-0.5 rounded-full text-xs font-bold text-white"
              [style.background]="statusGradient()"
            >
              {{ orderStatus() ?? 'PENDING' }}
            </span>
          </div>

          <p class="text-sm" [style.color]="statusTextColor()">{{ statusDetail() }}</p>

          <!-- Tracking info when shipped -->
          @if ((orderStatus() === 'SHIPPED' || orderStatus() === 'SHIPMENT_CREATED') && orderData()?.trackingId) {
            <div
              class="inline-flex items-center gap-2 px-4 py-2 rounded-xl border text-sm"
              style="background: rgba(52,211,153,0.1); border-color: rgba(52,211,153,0.3); color: #34d399;"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10" />
              </svg>
              Tracking: <span class="font-mono font-semibold">{{ orderData()?.trackingId }}</span>
            </div>
          }

          <!-- CTA buttons -->
          <div class="pt-2 space-y-2">
            <a
              routerLink="/"
              class="flex items-center justify-center gap-2 w-full py-3 rounded-xl text-sm font-bold text-white transition-all hover:scale-[1.02] hover:-translate-y-0.5 active:scale-[0.98]"
              style="background: var(--cc-grad-brand); box-shadow: var(--cc-shadow-btn);"
            >Continue Shopping</a>
            <a
              routerLink="/orders"
              class="flex items-center justify-center gap-2 w-full py-3 rounded-xl text-sm font-bold transition-all hover:scale-[1.01] hover:-translate-y-0.5"
              style="background: rgba(124,58,237,0.15); color: #a78bfa; border: 1.5px solid rgba(124,58,237,0.35);"
            >View My Orders</a>
          </div>
        </div>
      </div>
    </div>
  }

</div>

// cloudcart-frontend/app/checkout/page.tsx
"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { getCart, clearCart, CartItem } from "@/lib/cart";
import { useCart } from "@/lib/CartContext";
import { placeOrder, getOrder } from "@/lib/api";
import { useSession } from "@/lib/session";

const POLLING_TIMEOUT_MSG =
  "Order is being processed — check back shortly in My Orders.";

interface OrderStatus {
  orderId: string;
  status: "PENDING" | "PAID" | "SHIPMENT_CREATED" | "FAILED" | "TIMEOUT";
}

/* ── Shared icon helper ─────────────────────────────────────── */
function OrderStatusIcon({ status }: { status: OrderStatus["status"] }) {
  if (status === "SHIPMENT_CREATED") {
    return (
      <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10" />
      </svg>
    );
  }
  if (status === "PAID") {
    return (
      <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
      </svg>
    );
  }
  if (status === "FAILED") {
    return (
      <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
      </svg>
    );
  }
  // PENDING / TIMEOUT — animated spinner
  return (
    <span
      className="w-10 h-10 border-4 border-t-transparent rounded-full cc-spin inline-block"
      style={{ borderColor: "rgba(255,255,255,0.9)" }}
      aria-label="Processing"
    />
  );
}

export default function CheckoutPage() {
  const { refreshCartCount } = useCart();
  const session = useSession();
  const userId = session === undefined ? undefined : session?.userId ?? null;
  const [items, setItems] = useState<CartItem[]>([]);
  const [loadingCart, setLoadingCart] = useState(true);
  const [placing, setPlacing] = useState(false);
  const [orderStatus, setOrderStatus] = useState<OrderStatus | null>(null);
  const [error, setError] = useState<string | null>(null);

  const cancelledRef = useRef(false);
  useEffect(() => {
    cancelledRef.current = false;
    return () => { cancelledRef.current = true; };
  }, []);

  const fetchCart = useCallback(async () => {
    if (!userId) return;
    setLoadingCart(true);
    try {
      const data = await getCart(userId);
      setItems(data);
    } catch {
      setItems([]);
    } finally {
      setLoadingCart(false);
    }
  }, [userId]);

  useEffect(() => {
    if (userId) fetchCart();
    else if (userId === null) setLoadingCart(false);
  }, [userId, fetchCart]);

  const total = items.reduce((sum, i) => sum + i.price * i.quantity, 0);
  const totalQty = items.reduce((s, i) => s + i.quantity, 0);

  async function pollOrderStatus(orderId: string, uid: string) {
    const maxAttempts = 20;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      const delay = Math.min(2000 * Math.pow(1.3, attempt), 5000);
      await new Promise((r) => setTimeout(r, delay));
      if (cancelledRef.current) return;
      try {
        const order = await getOrder(orderId, uid);
        if (cancelledRef.current) return;
        setOrderStatus({ orderId, status: order.status as OrderStatus["status"] });
        if (order.status !== "PENDING") {
          if (order.status === "PAID" || order.status === "SHIPMENT_CREATED") {
            clearCart(uid).then(() => refreshCartCount()).catch(() => refreshCartCount());
          }
          return;
        }
      } catch {
        // keep polling
      }
    }
    setOrderStatus((prev) => prev ? { ...prev, status: "TIMEOUT" } : null);
  }

  async function handlePlaceOrder() {
    if (!userId || items.length === 0) return;
    setPlacing(true);
    setError(null);
    try {
      const orderItems = items.map((i) => ({
        productId: i.productId,
        quantity: i.quantity,
        price: i.price,
      }));
      const result = await placeOrder(userId, orderItems);
      setOrderStatus({ orderId: result.orderId, status: "PENDING" });
      await pollOrderStatus(result.orderId, userId);
    } catch {
      setError("Failed to place order. Please try again.");
    } finally {
      setPlacing(false);
    }
  }

  if (userId === undefined || loadingCart) return null;

  // ── No user ────────────────────────────────────────────────
  if (userId === null) {
    return (
      <div
        className="flex flex-col items-center justify-center py-24 rounded-3xl border cc-fade-up"
        style={{ borderColor: "var(--cc-border-vivid)", background: "var(--cc-surface-3)" }}
      >
        <div
          className="w-16 h-16 rounded-2xl flex items-center justify-center mb-5"
          style={{ background: "var(--cc-grad-brand)" }}
          aria-hidden="true"
        >
          <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
          </svg>
        </div>
        <p className="font-bold text-lg mb-1" style={{ color: "var(--cc-text-primary)" }}>
          No session active
        </p>
        <p className="text-sm mb-6" style={{ color: "var(--cc-text-secondary)" }}>
          Please log in first.
        </p>
        <Link
          href="/login"
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold text-white transition-all hover:scale-105"
          style={{ background: "var(--cc-grad-brand)", boxShadow: "var(--cc-shadow-md)" }}
        >
          Go to products
        </Link>
      </div>
    );
  }

  // ── Order status screen ─────────────────────────────────────
  if (orderStatus) {
    const isPending = orderStatus.status === "PENDING";
    const isPaid = orderStatus.status === "PAID";
    const isShipmentCreated = orderStatus.status === "SHIPMENT_CREATED";
    const isTimeout = orderStatus.status === "TIMEOUT";
    const isFailed = orderStatus.status === "FAILED";
    const isSuccess = isPaid || isShipmentCreated;

    const statusGrad = isSuccess
      ? "linear-gradient(135deg, #059669, #10b981)"
      : isFailed
      ? "linear-gradient(135deg, #dc2626, #ef4444)"
      : "linear-gradient(135deg, #d97706, #f59e0b)";

    const statusBg = isSuccess ? "#f0fdf4" : isFailed ? "#fef2f2" : "#fffbeb";
    const statusBorder = isSuccess ? "#bbf7d0" : isFailed ? "#fecaca" : "#fde68a";
    const statusTextColor = isSuccess ? "#065f46" : isFailed ? "#991b1b" : "#92400e";

    const statusLabel = isShipmentCreated
      ? "Shipment Created"
      : isPaid
      ? "Payment Successful"
      : isPending
      ? "Processing Payment"
      : isTimeout
      ? "Order Submitted"
      : "Payment Failed";

    const statusDetail = isShipmentCreated
      ? "Your order has been confirmed and a shipment is being prepared."
      : isPaid
      ? "Payment was processed successfully. Your order is confirmed."
      : isPending
      ? "Payment is being processed. This page updates automatically."
      : isTimeout
      ? POLLING_TIMEOUT_MSG
      : "The payment could not be processed. Please try again.";

    return (
      <div className="max-w-md mx-auto py-10 cc-fade-up" role="status" aria-live="polite">
        <div
          className="rounded-3xl overflow-hidden"
          style={{ border: `1px solid ${statusBorder}`, boxShadow: "var(--cc-shadow-lg)" }}
        >
          {/* Colored header */}
          <div
            className="flex flex-col items-center justify-center gap-4 py-10 px-8"
            style={{ background: statusGrad }}
          >
            <div
              className="w-20 h-20 rounded-full flex items-center justify-center"
              style={{ background: "rgba(255,255,255,0.2)" }}
            >
              <OrderStatusIcon status={orderStatus.status} />
            </div>
            <h2 className="text-2xl font-black text-white text-center">
              {statusLabel}
            </h2>
          </div>

          {/* Details */}
          <div style={{ background: statusBg }} className="px-8 py-6 text-center space-y-4">
            <div
              className="inline-flex flex-col items-center gap-1 px-5 py-3 rounded-2xl border"
              style={{ borderColor: statusBorder }}
            >
              <p className="text-xs font-bold uppercase tracking-widest" style={{ color: statusTextColor }}>
                Order ID
              </p>
              <p className="font-mono text-sm font-semibold" style={{ color: "var(--cc-text-primary)" }}>
                {orderStatus.orderId}
              </p>
              <span
                className="mt-1 px-2.5 py-0.5 rounded-full text-xs font-bold"
                style={{ background: statusGrad, color: "#fff" }}
              >
                {isTimeout ? "PENDING" : orderStatus.status}
              </span>
            </div>

            <p className="text-sm" style={{ color: statusTextColor }}>
              {statusDetail}
            </p>

            <div className="pt-2 space-y-2">
              <Link
                href="/"
                className="flex items-center justify-center gap-2 w-full py-3 rounded-xl text-sm font-bold text-white transition-all hover:scale-[1.02] hover:-translate-y-0.5 active:scale-[0.98]"
                style={{ background: "var(--cc-grad-brand)", boxShadow: "var(--cc-shadow-btn)" }}
              >
                Continue Shopping
              </Link>
              <Link
                href="/orders"
                className="flex items-center justify-center gap-2 w-full py-3 rounded-xl text-sm font-bold transition-all hover:scale-[1.01] hover:-translate-y-0.5"
                style={{
                  background: "var(--cc-surface-3)",
                  color: "var(--cc-violet-dark)",
                  border: "1.5px solid var(--cc-border-vivid)",
                  boxShadow: "var(--cc-shadow-sm)",
                }}
              >
                View My Orders
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ── Checkout form ───────────────────────────────────────────
  return (
    <div className="max-w-2xl mx-auto cc-fade-up">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-black" style={{ color: "var(--cc-text-primary)" }}>
            Checkout
          </h1>
          {items.length > 0 && (
            <p className="text-sm mt-0.5" style={{ color: "var(--cc-text-muted)" }}>
              Review your order before placing it
            </p>
          )}
        </div>
        <Link
          href="/cart"
          className="inline-flex items-center gap-1.5 text-sm font-semibold transition-colors duration-150"
          style={{ color: "var(--cc-violet)" }}
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to cart
        </Link>
      </div>

      {/* Empty cart */}
      {items.length === 0 ? (
        <div
          className="flex flex-col items-center justify-center py-24 rounded-3xl border"
          style={{ borderColor: "var(--cc-border-vivid)", background: "var(--cc-surface-3)" }}
        >
          <div
            className="w-16 h-16 rounded-2xl flex items-center justify-center mb-5"
            style={{ background: "var(--cc-grad-brand)" }}
            aria-hidden="true"
          >
            <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
          </div>
          <p className="text-lg font-black mb-2" style={{ color: "var(--cc-text-primary)" }}>
            Your cart is empty
          </p>
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-bold text-white mt-2 transition-all hover:scale-105"
            style={{ background: "var(--cc-grad-brand)", boxShadow: "var(--cc-shadow-md)" }}
          >
            Browse products
          </Link>
        </div>
      ) : (
        <div className="space-y-4">
          {/* Order summary card */}
          <div
            className="rounded-2xl overflow-hidden"
            style={{
              background: "var(--cc-surface-card)",
              border: "1px solid var(--cc-border)",
              boxShadow: "var(--cc-shadow-sm)",
            }}
          >
            <div
              className="px-6 py-4 border-b"
              style={{ background: "var(--cc-surface-3)", borderColor: "var(--cc-border-vivid)" }}
            >
              <h2
                className="text-xs font-bold uppercase tracking-widest"
                style={{ color: "var(--cc-violet)" }}
              >
                Order Summary
              </h2>
            </div>
            <div className="px-6 py-4 divide-y" style={{ "--tw-divide-opacity": 1 } as React.CSSProperties}>
              {items.map((item) => (
                <div
                  key={item.productId}
                  className="flex justify-between items-center py-3 first:pt-0 last:pb-0"
                >
                  <div className="min-w-0">
                    <p
                      className="text-sm font-semibold truncate"
                      style={{ color: "var(--cc-text-primary)" }}
                    >
                      {item.title || item.productId}
                    </p>
                    <p className="text-xs mt-0.5" style={{ color: "var(--cc-text-muted)" }}>
                      Qty: {item.quantity} &times; ${item.price.toFixed(2)}
                    </p>
                  </div>
                  <span className="font-bold text-sm ml-4" style={{ color: "var(--cc-text-primary)" }}>
                    ${(item.price * item.quantity).toFixed(2)}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Total bar */}
          <div
            className="flex justify-between items-center px-6 py-4 rounded-2xl"
            style={{
              background: "var(--cc-surface-3)",
              border: "1px solid var(--cc-border-vivid)",
            }}
          >
            <span className="font-bold" style={{ color: "var(--cc-text-primary)" }}>
              Total ({totalQty} item{totalQty !== 1 ? "s" : ""})
            </span>
            <span className="text-2xl font-black cc-gradient-text">
              ${total.toFixed(2)}
            </span>
          </div>

          {/* Error */}
          {error && (
            <div
              className="flex items-start gap-3 px-5 py-4 rounded-2xl border text-sm"
              style={{ background: "#fef2f2", borderColor: "#fecaca", color: "#991b1b" }}
              role="alert"
            >
              <svg className="w-5 h-5 mt-0.5 shrink-0" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" aria-hidden="true">
                <circle cx="12" cy="12" r="10" />
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4m0 4h.01" />
              </svg>
              <p>{error}</p>
            </div>
          )}

          {/* Place order button */}
          <button
            onClick={handlePlaceOrder}
            disabled={placing}
            className="w-full flex items-center justify-center gap-3 py-4 rounded-2xl text-base font-black text-white transition-all duration-150 disabled:opacity-60 disabled:cursor-not-allowed hover:scale-[1.02] hover:-translate-y-0.5 active:scale-[0.98]"
            style={{
              background: "var(--cc-grad-brand)",
              boxShadow: "var(--cc-shadow-btn)",
            }}
          >
            {placing ? (
              <>
                <span
                  className="w-5 h-5 border-2 border-t-transparent rounded-full cc-spin"
                  style={{ borderColor: "rgba(255,255,255,0.8)" }}
                  aria-hidden="true"
                />
                Placing Order…
              </>
            ) : (
              <>
                <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" aria-hidden="true">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Place Order &mdash; ${total.toFixed(2)}
              </>
            )}
          </button>

          <p className="text-center text-xs" style={{ color: "var(--cc-text-muted)" }}>
            By placing your order you agree to our demo terms. All transactions are simulated.
          </p>
        </div>
      )}
    </div>
  );
}
